### PR TITLE
Add webgl backend support unit test

### PR DESCRIPTION
**Pull request by haoyunfeix**

### CODE REVIEW

**Comment by haoyunfeix** [comment]
Use `yarn test-opengl` and `yarn d3d` for webgl backend UT.

**Comment by qjia7** [comment]
Thanks Yunfei. The change looks good for me. BTW, do you try if all the cases can pass when using `yarn test-opengl` and `yarn d3d`?

**Comment by qjia7** [comment]
Please add this sentence 'Use yarn test-opengl and yarn d3d for webgl backend UT.' to your commit message so that others know how to use it.

**Comment by qjia7** [comment]
LGTM. Thanks.

**Pull request merged**
